namespace Bogosoft.Hashing
{
    /// <summary>
    /// Indicates that an implementation is capable of generating a fixed-length
    /// sequence of bytes given a variable-length sequence of bytes.
    /// </summary>
    public interface IHash
    {
        /// <summary>
        /// Get a value corresponding to the length of the sequence of bytes
        /// generated by the current hashing strategy.
        /// </summary>
        int HashLength { get; }

        /// <summary>
        /// Generate a fixed-length sequence of bytes against a variable-length sequence of bytes.
        /// </summary>
        /// <param name="bytes">A variable-length sequence of bytes.</param>
        /// <returns>
        /// A fixed-length sequence of bytes.
        /// </returns>
        byte[] Compute(byte[] bytes);
    }
}