namespace Bogosoft.Hashing
{
    /// <summary>
    /// Indicates that an implementation is capable of generating a fixed-length
    /// sequence of bytes given an object of <see cref="IHashable"/>.
    /// </summary>
    public interface IHash
    {
        /// <summary>
        /// Get a value corresponding to the length of the sequence of bytes
        /// generated by the current hashing strategy.
        /// </summary>
        int HashLength { get; }

        /// <summary>
        /// Generate a fixed-length sequence of bytes against a given <see cref="IHashable"/> object.
        /// </summary>
        /// <param name="object">An object to hash.</param>
        /// <returns>
        /// A fixed-length sequence of bytes.
        /// </returns>
        byte[] Compute(IHashable @object);
    }
}